plugins {
    id 'com.android.application'
}

android {
    namespace 'com.retaillink.f20.installtest'
    compileSdk 36

    defaultConfig {
        applicationId 'com.retaillink.f20.installtest'
        minSdk 23
        targetSdk 29
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        debug {
            enableV1Signing true
            enableV2Signing true
            enableV3Signing false
            enableV4Signing false
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            debuggable false
            minifyEnabled false
        }
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
